name: build
on:
  push:
    branches:
      - '*'
permissions:
  contents: read
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5.5.0
      with:
        go-version: '1.24'
        cache: true
      id: go
    - uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: "~> v2"
        args: build --snapshot --clean
    - run: go test -v ./...
