name: Go
on:
  push:
    branches: main
permissions:
  contents: read

jobs:
  build:
    name: Go Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version: '1.24'
        cache: true
      id: go

    - name: Build
      env:
        GO111MODULE: on
      run: go build -v .

    - name: Test
      env:
        GO111MODULE: on
      run: go test -v ./...